console.log("Izzatillo");
console.log(08);
console.log("03");
console.log("'Добро ' + 'пожаловать ' + ' на курс'");
// alert('2019');
// alert(2019-200);
document.getElementById('one').innerHTML = 'Hello World';
document.getElementById('two').innerHTML = 12 * 12 ;
document.querySelector('.one').innerHTML = 'Hello World';
document.querySelector('h2 span').innerHTML = 'world';
let three = document.querySelector('.three');
three.innerHTML = '<h3>TUt proizvolniy text</h3>';
let four = document.querySelector('.four');
four.innerHTML = "<h4>Tut 4to to proizvlonoe <p>I paragraf proizvloniy</p> </h4>";
let a =  document.querySelector('.five');
a.innerHTML = 3.1415;
let div7 = document.querySelector('.seven');
div7.innerHTML = `<img src="https://cdn4.iconfinder.com/data/icons/food-and-drink-flat-gradient/32/cone_ice_cream_food_drink_sweet-512.png" alt="">`;
z1=6;
z2=3;
let multiplication = document.querySelector('.multiplication');
multiplication.innerHTML = z1 * z2;
x1 =  'Hello';
x2 = 5;
let addition = document.querySelector('.addition');
addition.innerHTML = x1+x2;
let d1 = document.querySelector('.test-1');
console.log(d1);
d2 = document.querySelector('.test-2');
console.log(d2);
d2 = 5;
console.log(d2);
let divS3 = document.querySelector('.s3');
console.log(divS3);
divS3 = document.querySelector('.s4');
console.log(divS3);

// let body = document.querySelector('body');
// body.innerHTML = '';